# Generated by Django 6.0 on 2026-01-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='has_facial_data',
            field=models.BooleanField(default=False),
        ),
    ]
