# Generated by Django 6.0 on 2026-02-01 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schedules', '0002_group_module'),
        ('students', '0004_alter_students_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='schedules.group'),
        ),
    ]
