version: "3.9"
services:
  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  backend:
    image: academiazz-app
    ports:
      - "8000:8000"
    volumes:
      - ./academiazz:/app
    env_file:
      - ./vars/.env
    depends_on:
      - redis

  celery:
    image: academiazz-app             
    command: celery -A academiazz worker --loglevel=info --pool=solo
    volumes:
      - ./academiazz:/app
    env_file:
      - ./vars/.env
    depends_on:
      - backend
      - redis

  celery_beat:
    image: academiazz-app             
    command: celery -A academiazz beat --loglevel=info
    volumes:
      - ./academiazz:/app
    env_file:
      - ./vars/.env
    depends_on:
      - backend
      - redis

  # frontend:
  #   build: ./frontend
  #   ports:
  #     - "5173:5173"
  #   volumes:
  #     - ./frontend:/app
  #     - /app/node_modules

volumes:
  media_files:      
  faiss_indexes:     