# Generated by Django 6.0 on 2026-01-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='uploaded_by',
            field=models.CharField(max_length=255),
        ),
    ]
