# Generated by Django 6.0 on 2026-01-24 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_resource_uploaded_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='file',
            field=models.FileField(upload_to='resources/pdfs/'),
        ),
    ]
