# Generated by Django 6.0 on 2026-01-25 04:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0004_module'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.module'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='week',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
