# Generated by Django 6.0 on 2026-04-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_resource_description_alter_resource_module_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='type',
            field=models.CharField(choices=[('lecture', 'Lecture'), ('tutorial', 'Tutorial'), ('workshop', 'Workshop')], default='lecture', max_length=20),
        ),
    ]
