# Generated by Django 6.0 on 2026-05-10 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0006_resource_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='public/pdfs/')),
                ('title', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('type', models.CharField(choices=[('enrollment', 'Enrollment'), ('courses', 'Courses'), ('location', 'Location'), ('fees', 'Fees'), ('requirements', 'Entry Requirements'), ('faq', 'FAQ'), ('general', 'General')], default='general', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
