# Generated by Django 6.0 on 2026-05-23 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0007_publicdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='semester',
            field=models.IntegerField(choices=[(1, 'Semester 1'), (2, 'Semester 2'), (3, 'Semester 3'), (4, 'Semester 4'), (5, 'Semester 5'), (6, 'Semester 6')], default=1),
        ),
        migrations.AddField(
            model_name='module',
            name='year',
            field=models.IntegerField(choices=[(1, 'Year 1'), (2, 'Year 2'), (3, 'Year 3')], default=1),
        ),
    ]
