# Generated by Django 6.0 on 2026-03-07 16:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schedules', '0004_alter_schedule_options_remove_schedule_date_and_more'),
        ('students', '0005_alter_students_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('past', 'Past'), ('today', 'Today'), ('future', 'Future')], default='future', max_length=10)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='schedules.schedule')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('schedule', 'date')},
            },
        ),
        migrations.CreateModel(
            name='AttendanceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('status', models.CharField(choices=[('present', 'Present'), ('absent', 'Absent'), ('late', 'Late')], default='absent', max_length=10)),
                ('marked_at', models.DateTimeField(default=django.utils.timezone.localtime)),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schedule', to='schedules.schedule')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attendance_history', to='students.students')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='attendance_history', to='attendance.classsession')),
            ],
            options={
                'unique_together': {('student', 'schedule', 'date')},
            },
        ),
    ]
