# Generated by Django 6.0 on 2026-03-22 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancehistory',
            unique_together=set(),
        ),
    ]
