# Generated by Django 6.0 on 2026-02-01 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_resource_description_alter_resource_module_and_more'),
        ('schedules', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='groups', to='resources.module'),
        ),
    ]
