# Generated by Django 6.0 on 2026-02-01 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_alter_resource_description_alter_resource_module_and_more'),
        ('schedules', '0002_group_module'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='module',
        ),
        migrations.AddField(
            model_name='group',
            name='module',
            field=models.ManyToManyField(related_name='groups', to='resources.module'),
        ),
    ]
